version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pedidos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pedidos
    ports:
      - "5432:5432"
    volumes:
      - pedidos-db-data:/var/lib/postgresql/data
      - ./db/migration:/docker-entrypoint-initdb.d #Scripts de inicializaci√≥n por orden
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pedidos-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80" # pgAdmin web UI (localhost:8081)
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pedidos-db-data:
  pgadmin-data:
