spring:
  application:
    name: pedidos-service

server:
  port: 8080

# Config com√∫n
app:
  db:
    kind: ${DB_KIND:H2}
    url: ${DB_URL:jdbc:h2:mem:pedidos}
    user: ${DB_USER:sa}
    pass: ${DB_PASS:}
